### ISSUE TITLE
Manual registration broken in v3.0.0

### ISSUE THREAD

**Issue by Jimmys20** [jsakamoto/Toolbelt.Blazor.PWA.Updater#22]
Hello, the following code no longer works in v3.0.0 throwing `TypeError: Toolbelt.Blazor.PWA.Updater.handleRegistration is not a function`:

```
<script src="_content/Toolbelt.Blazor.PWA.Updater.Service/script.min.js" no-register></script>
<script>
  navigator.serviceWorker.register('service-worker.js', { updateViaCache: 'none' }).then(registration => {
    Toolbelt.Blazor.PWA.Updater.handleRegistration(registration);
  });
</script>
```

This happens because in no-register mode `handleRegistration` is not called so `Updater.handleRegistration = handleRegistration;` is never set.

https://github.com/jsakamoto/Toolbelt.Blazor.PWA.Updater/blob/c50317aca566f71875f202b903b567365abda498/Updater.Service/script.js#L41-L56

This change created the issue: https://github.com/jsakamoto/Toolbelt.Blazor.PWA.Updater/commit/6700f713f9031275abf9a0130beb2d56ecbd3711#diff-2fd7e9fad2e9ad96bed8d947cf72c69d8b8091498b9266dde80955e18213511fL40

**Comment by jsakamoto** [comment]
@Jimmys20 Thank you for letting me know that! Your report is very helpful to us. I'll investigate this issue. Thanks!

**Comment by jsakamoto** [comment]
@Jimmys20 I have just published the new version, 3.0.1, right now. Could you please try it out? Thank you for your contributions!

**Comment by Jimmys20** [comment]
It is fixed in v3.0.1, thank your very much!

I wonder if `Updater.handleRegistration = handleRegistration;` was done inside `handleRegistration` after `notifyNextVersionIsWaitingToBlazor(waiting);` and `monitor(waiting);` for some good reason? Maybe it shouldn't be exported earlier?

**Comment by jsakamoto** [comment]
I'm sure there is no reason. It must be just an editing mistake for me. I don't remember well, but when I was moving the line down, that editing operation might have been interrupted for some reason, such as my laptop's battery running out. And I forgot that, I believe.😭

**Comment by jsakamoto** [comment]
My most critical mistake is that I haven't written tests for the manual registration feature. If I did it, the tests must detect such an editing mistake. I'll add new test suites for the manual registration feature as soon as I can.
